//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Personator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:MelissaDataPersonator", ConfigurationName="Personator.ServicemdContactVerifySOAP")]
    public interface ServicemdContactVerifySOAP {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerify", ReplyAction="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerifyResponse")]
        DataClean.Personator.Response doContactVerify(DataClean.Personator.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerify", ReplyAction="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerifyResponse")]
        System.Threading.Tasks.Task<DataClean.Personator.Response> doContactVerifyAsync(DataClean.Personator.Request Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicemdContactVerifySOAPChannel : ConsoleApplication1.Personator.ServicemdContactVerifySOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicemdContactVerifySOAPClient : System.ServiceModel.ClientBase<ConsoleApplication1.Personator.ServicemdContactVerifySOAP>, ConsoleApplication1.Personator.ServicemdContactVerifySOAP {
        
        public ServicemdContactVerifySOAPClient() {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicemdContactVerifySOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataClean.Personator.Response doContactVerify(DataClean.Personator.Request Request) {
            return base.Channel.doContactVerify(Request);
        }
        
        public System.Threading.Tasks.Task<DataClean.Personator.Response> doContactVerifyAsync(DataClean.Personator.Request Request) {
            return base.Channel.doContactVerifyAsync(Request);
        }
    }
}
